#!/bin/bash
#Install useful terminal programs

echo "fzf installation"
echo
mkdir ~/repos/
git clone https://github.com/junegunn/fzf.git ~/repos/
~/repos/fzf/install

echo
echo "Install fish, neovim, ncdu, htop, tree, neofetch, git, curl, openssh-server, openssh-client, python3"
echo
sudo apt install fish neovim ncdu htop tree neofetch git curl openssh-server openssh-client python3 -y

echo
echo "Install bat, gotop"
echo 
sudo snap install batcat gotop-brlin

echo 
echo "install navi"
echo
bash <(curl -sL https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install)


echo 
echo "install npm and nodejs"
echo
sudo apt install nodejs npm -y

echo
echo "install speedtest"
echo
sudo npm install --global speed-test

echo
echo "Make fish default"
echo
chsh -s `which fish`


echo
echo "Clean apt"
echo 
sudo apt autoremove -y

echo
echo "########## Rebooting system in 15 s ##########"
echo "After reboot run configure_programs"
sleep 5 
( sleep 15 ; reboot ) & 

echo
echo "Install fish plugins"
echo 
curl -L https://get.oh-my.fish | fish &