#!/bin/bash
echo "Update apt packages"
echo 
sudo apt update && sudo apt upgrade -y
sudo apt autoremove -y

echo 
echo "Update node"
echo 
sudo n stable

echo
echo "Update npm packages"
echo 
sudo npm update -g
sudo npm install -g npm@latest
sudo npm audit fix

echo
echo "Update snap"
echo 
sudo snap refresh core
sudo snap refresh

echo
echo "Update navi"
echo 
rm -dfr ~/.local/share/navi/cheats/Tekofx__navi-cheats
navi repo add https://github.com/Tekofx/navi-cheats.git

